eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:3000/eureka/
server :
  port : 3001
  shutdown : graceful
spring :
  config :
    import : configserver:${CONFIGSERVER_IMPORT:http://localhost:3002}
