eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:3000/eureka/
server :
  port : 3002
  shutdown : graceful
  forward-headers-strategy : framework
  tomcat :
    redirect-context-root : false
