spring :
  devtools :
    add-properties : true
    restart :
      enabled : true
    livereload :
      enabled : true
management :
  endpoints :
    enabled-by-default : true

server :
  port : 3005

eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:3000/eureka/

springdoc :
  show-actuator : true